# O MySQL não foi feito o sistema ainda...
database:
  type: 'sqlite'
  mysql:
    address: 'localhost:3306'
    username: 'root'
    password: ''
    database: 'test'
  sqlite:
    file: 'database/database.db'

Restart:
  Message_In_Time: '&a&lREINICIO: &fRestam &7%s &fsegundos para o server ser reinicado.'
  Message_Restart_Now: '§a§lREINICIO: §fReiniciando o servídor.'
  Message_On_Interact_Items:
    - ''
    - '&cVocê não pode abrir esses items pois o servidor'
    - '&cestá reiniciando, aguarde...'
    - ''
  Message_On_Interact_Commands:
    - ''
    - '&cVocê não pode executar comandos pois o servidor'
    - '&cestá reiniciando, aguarde...'
    - ''

Message:
  Gamemode_Change: '&aSeu modo de jogo foi alterado para %s!'
  Gamemode_Change_Player: '&aO modo de jogo de %s foi alterado para %s.'
  Gamemode_Invalid: '&cEste modo de jogo é inválido!'
  Gamemode_Same_Player: '&cVocê não pode alterar o modo de jogo de sí mesmo!'
  No_Permissions: '&cVocê não tem permissão para executar esse comando!'
  Incorect_Target: '&cEsse comando não pode ser executado aqui!'
  Feed_Max: '&cSua fome está cheia.'
  Feed_Satiated: '&aSua fome foi saciada com êxito.'
  Feed_Full_Player: '&cA fome deste jogador já está cheia.'
  Feed_Regenerated_Player: '&eFome de &f%s &efoi saciada com êxito.'
  Feed_Regenerated_By_Player: '&eSua fome foi saciada por &f%s&e.'
  Maintence_Kick: '&cOlá %s você infelizemente foi kickado!'
  Website: '&aO site do nosso servidor é &fwww.seusite.com.br'
  Clear_Chat: '&aO chat foi limpo por &2%s&a!'
  Trash_Title: '&8Lixeira de %s.'
  Players_Online: '&aEstamos com &f%s &ajogadores online!'
  Just_You_Online: '&aApenas você online no servidor.'
  Crashed_Player: '&aVocê crashou o minecraft de %s.'
  Crashed_Player_Not_Online: '&cO jogador que você tentou crashar não está online.'
  Teleport_To_Yourself: '&cVocê não pode ir até si mesmo.'
  Teleport_Player_Offline: '&cEsse jogador não está online.'
  Teleported_To_Player: '&aVocê foi teleportado até %s, com sucesso!'
  Teleported_To_You: '&aO jogador %s foi teleportado até você.'
  Join_server:
    title: "&6&lSEU SERVIDOR"
    subtitle: "&florem ipsum"
